apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docker-event-pipeline

resources:
  - namespace.yaml
  - app-configmap.yaml
  - app-secret.example.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
